### ISSUE TITLE
No version key in manifest file

### ISSUE THREAD

**Issue by astranberg** [robert-alfaro/xfinity-usage#11]
Logger: homeassistant.loader
Source: loader.py:794
First occurred: 3:46:11 PM (1 occurrences)
Last logged: 3:46:11 PM

No 'version' key in the manifest file for custom integration 'xfinity'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'xfinity'

**Comment by robert-alfaro** [comment]
Thank you for reporting.  I will get the version string in manifest soon.  Although the integration may still be broken...

**Comment by skynet01** [comment]
Any updates on this? Would be amazing to get it working again

**Comment by robert-alfaro** [comment]
let me know if fixed by 8e8e5f0

**Comment by astranberg** [comment]
> let me know if fixed by [8e8e5f0](https://github.com/robert-alfaro/xfinity-usage/commit/8e8e5f0731d236f9de50bb4631722823f8bb41b9)

So HACS doesn't see that there's an update. However, I have edited the manifest file manually, but I can't test it because....

HA now says xfinity doesn't exit....
