### ISSUE TITLE
Platform error sensor.xfinity - Integration 'xfinity' not found.

### ISSUE THREAD

**Issue by astranberg** [robert-alfaro/xfinity-usage#12]
Not sure if this is the plugin or me? I'm getting this error when I check configuration.yaml:

> Platform error sensor.xfinity - Integration 'xfinity' not found.

My YAML is valid on an online validator.

`
sensor:
  - platform: xfinity
    username: !secret xfinity_email
    password: !secret xfinity_password
`

Uninstalling and re-installing via HACS didn't work.

Downloading and installing manually didn't work.

I'm really at a loss here....

**Comment by chriskob** [comment]
Same here

**Comment by chriskob** [comment]
Same here

**Comment by rock425a** [comment]
I was getting the same results:

Platform error sensor.xfinity - Integration 'xfinity' not found.

I found that it was complaining of no version info in the manifest.json file - 

if you go to this file:  /config/custom_components/xfinity/manifest.json 

and add the following:
  "version": "0.1.0",

between name and documentation, this will allow the integration to load (may need to restart home assistant).

The issue I'm seeing now is failure to authenticate...

@robert-alfaro - for some reason, it appears that hacs isn't pulling the full repo down,  I noticed in the manifest.json file, you are missing the comma at the end of the version line - I'm not sure if this is the reason it's not updating or not.

**Comment by astranberg** [comment]
**EDIT**

```
{
  "domain": "xfinity",
  "name": "Xfinity Usage",
  "version": "0.1.0",
  "documentation": "https://github.com/robert-alfaro/xfinity-usage",
  "requirements": [],
  "dependencies": [],
  "codeowners": [
    "@ralfaro"
  ]
}
```

I can confirm that version is missing a comma. Adding it fixes this.

**Comment by robert-alfaro** [comment]
add missing comma 1737ab8

**Comment by astranberg** [comment]
> add missing comma [1737ab8](https://github.com/robert-alfaro/xfinity-usage/commit/1737ab85c30c007e0806d95d70040fa1a903a8d4)

this works. can be closed.
